name: Nuclear Clean

on:
  schedule:
    - cron: '0 16,4 * * *'  # 北京时间0:00和12:00
  workflow_dispatch:

jobs:
  obliterate:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      actions: write
      contents: write

    steps:
      - name: Install tools
        run: |
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo gpg --dearmor -o /usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list
          sudo apt update
          sudo apt install gh jq -y

      - name: Cleanup Workflow Runs
        run: |
          gh api -H "Authorization: Bearer $GH_TOKEN" "/repos/$REPO/actions/runs?per_page=100" \
            --paginate -q ".workflow_runs[] | select(.id != $RUN_ID) | .id" | \
            xargs -I {} gh api -X DELETE "/repos/$REPO/actions/runs/{}" -H "Authorization: Bearer $GH_TOKEN"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          RUN_ID: ${{ github.run_id }}

      - name: Purge All Caches (verified)
        run: |
          # 获取所有缓存ID并删除
          cache_ids=$(gh api -H "Authorization: Bearer $GH_TOKEN" "/repos/$REPO/actions/caches" \
            --paginate -q '.cache_entries[].id' 2>/dev/null || true)
          
          if [ -n "$cache_ids" ]; then
            echo "$cache_ids" | xargs -I {} sh -c 'gh api -X DELETE "/repos/$REPO/actions/caches/{}" -H "Authorization: Bearer $GH_TOKEN"'
            echo "Deleted ${cache_ids} caches"
          else
            echo "No caches found"
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}

      - name: Remove Releases
        run: |
          release_ids=$(gh api -H "Authorization: Bearer $GH_TOKEN" "/repos/$REPO/releases" \
            --paginate -q '.[].id' 2>/dev/null || true)
          
          if [ -n "$release_ids" ]; then
            echo "$release_ids" | xargs -I {} gh api -X DELETE "/repos/$REPO/releases/{}" -H "Authorization: Bearer $GH_TOKEN"
          else
            echo "No releases found"
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          
      - name: Delete All Tags
        run: |
          tags=$(gh api -H "Authorization: Bearer $GH_TOKEN" "/repos/$REPO/tags" --paginate -q '.[].name' 2>/dev/null || true)
          if [ -n "$tags" ]; then
            echo "$tags" | xargs -I {} gh api -X DELETE "/repos/$REPO/git/refs/tags/{}" -H "Authorization: Bearer $GH_TOKEN"
          else
            echo "No tags found"
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
