name: Auto Cleanup Repository

on:
  schedule:
    - cron: '0 16,4 * * *'  # UTC时间每天4:00和16:00运行（对应北京时间12:00和24:00）
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
      packages: write
    steps:
      - name: Cleanup Workflow Runs
        run: |
          gh api -X DELETE /repos/${{ github.repository }}/actions/runs \
            -f "per_page=100" \
            --paginate \
            --jq ".workflow_runs[] | select(.status != \"in_progress\") | .id" \
            | xargs -I {} gh api -X DELETE /repos/${{ github.repository }}/actions/runs/{}

      - name: Delete Releases
        run: |
          gh api -X GET /repos/${{ github.repository }}/releases --paginate \
            --jq ".[].id" \
            | xargs -I {} gh api -X DELETE /repos/${{ github.repository }}/releases/{}

      - name: Delete Tags
        run: |
          gh api -X GET /repos/${{ github.repository }}/git/refs/tags --paginate \
            --jq ".[].ref" \
            | sed 's/refs\/tags\///' \
            | xargs -I {} gh api -X DELETE /repos/${{ github.repository }}/git/refs/tags/{}

      - name: Cleanup Caches
        run: |
          gh actions cache list --all --limit 100 | grep -v " Total " | awk '{print $1}' \
            | xargs -I {} gh actions cache delete --cache-id {} --confirm

      - name: Cleanup Artifacts
        run: |
          gh api -X GET /repos/${{ github.repository }}/actions/artifacts --paginate \
            --jq ".artifacts[].id" \
            | xargs -I {} gh api -X DELETE /repos/${{ github.repository }}/actions/artifacts/{}
