name: Official Repository Cleanup

on:
  schedule:
    - cron: '0 0 * * *'  # UTC 0点 → 中国时间8点
    - cron: '0 12 * * *' # UTC 12点 → 中国时间20点
  workflow_dispatch:

permissions:
  actions: write
  contents: write
  pull-requests: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate with GitHub CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token --scope repo,workflow,delete-repo

      - name: Clean workflows
        run: gh run list --repo "${{ github.repository }}" --all --json databaseId | jq -r '.[].databaseId' | xargs -I{} gh run delete {} --yes

      - name: Clean releases
        run: gh release list --repo "${{ github.repository }}" --json id | jq -r '.[].id' | xargs -I{} gh release delete {} --yes

      - name: Clean tags
        run: gh tag list --repo "${{ github.repository }}" --json name | jq -r '.[].name' | xargs -I{} gh tag delete {} --force --yes

      - name: Clean caches
        run: gh cache clean --all --yes --repo "${{ github.repository }}"
