name: Clean Repo

on:
  schedule:
    - cron: '0 0 * * *'  # UTC 0点 → 中国时间8点
    - cron: '0 12 * * *' # UTC 12点 → 中国时间20点
  workflow_dispatch:

permissions:
  actions: write
  contents: write

jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - name: Setup GH CLI
        uses: actions/setup-gh@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete workflows
        run: |
          gh run list --repo "${{ github.repository }}" --all --json databaseId \
          | jq -r '.[].databaseId' \
          | grep -v "${{ github.run_id }}" \
          | xargs -I{} gh run delete {} --yes --repo "${{ github.repository }}"

      - name: Delete releases
        run: gh release list --repo "${{ github.repository }}" --json id | jq -r '.[].id' | xargs -I{} gh release delete {} --yes --repo "${{ github.repository }}"

      - name: Delete tags
        run: gh tag list --repo "${{ github.repository }}" --json name | jq -r '.[].name' | xargs -I{} gh tag delete {} --force --yes --repo "${{ github.repository }}"

      - name: Clean caches
        run: gh cache clean --all --yes --repo "${{ github.repository }}"
