name: Nuclear Clean

on:
  schedule:
    - cron: '0 16,4 * * *'
  workflow_dispatch:

jobs:
  obliterate:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
      packages: write

    steps:
      - name: Clean Workflow Runs
        run: |
          sudo apt update
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          sudo apt install gh -y
          gh api -H "Authorization: Bearer $GH_TOKEN" "/repos/$REPO/actions/runs" -q ".workflow_runs[].id" | xargs -I {} gh api -X DELETE "/repos/$REPO/actions/runs/{}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}

      - name: Purge All Caches
        run: |
          gh api -H "Authorization: Bearer $GH_TOKEN" "/repos/$REPO/actions/caches?per_page=100" -q '.cache_entries[].id' | xargs -I {} gh api -X DELETE "/repos/$REPO/actions/caches/{}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}

      - name: Delete All Releases
        run: |
          gh api -H "Authorization: Bearer $GH_TOKEN" "/repos/$REPO/releases" -q '.[].id' | xargs -I {} gh api -X DELETE "/repos/$REPO/releases/{}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}

      - name: Delete All Tags
        run: |
          gh api -H "Authorization: Bearer $GH_TOKEN" "/repos/$REPO/git/refs/tags" -q '.[].ref' | xargs -I {} gh api -X DELETE "/repos/$REPO/git/{}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
