name: Auto-Clean Repository

on:
  schedule:
    - cron: '0 16,4 * * *'  # 每天UTC 04:00 & 16:00 (北京时间12:00 & 00:00)
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
      packages: write
      
    steps:
      # 清理工作流历史
      - name: Purge workflow runs
        run: |
          while read run_id; do
            gh api -X DELETE "/repos/$GITHUB_REPOSITORY/actions/runs/$run_id" \
              --silent \
              --header "Authorization: token $GH_TOKEN"
          done < <(gh run list --json databaseId -q '.[].databaseId')
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 清理缓存
      - name: Clear all caches
        run: |
          while read id; do
            gh api -X DELETE "/repos/$GITHUB_REPOSITORY/actions/caches/$id" \
              --silent \
              --header "Authorization: token $GH_TOKEN"
          done < <(gh api /repos/$GITHUB_REPOSITORY/actions/caches | jq -r '.actions_caches[].id')
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 清理标签和发布
      - name: Remove tags and releases
        run: |
          # 删除所有发布
          while read tag; do
            gh release delete "$tag" --cleanup-tag --yes
          done < <(gh release list --json tagName -q '.[].tagName')
          
          # 删除所有标签
          while read tag; do
            git push origin ":refs/tags/$tag"
          done < <(git tag -l)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
