name: Nuclear Clean

on:
  schedule:
    - cron: '0 16,4 * * *'
  workflow_dispatch:

jobs:
  obliterate:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      actions: write
      contents: write
      packages: write
      
    steps:
      - name: Install GitHub CLI
        run: |
          type -p gh >/dev/null || (sudo apt update && sudo apt install -y gh)
          
      - name: Execute Nuclear Clean
        run: |
          # 强制初始化GitHub CLI
          gh auth setup-git --token "$GITHUB_TOKEN"
          
          # 清理工作流运行
          CURRENT_RUN_ID=${{ github.run_id }}
          gh run list -L 100 -q ".[] | select(.databaseId != $CURRENT_RUN_ID).databaseId" | xargs -r gh run delete -y
          
          # 清理缓存
          gh cache delete --all --confirm
          
          # 清理发布和标签
          gh release list -L 100 -q ".[].tagName" | xargs -r gh release delete -y --cleanup-tag
          
          # 清理残留标签
          gh api /repos/${{ github.repository }}/tags?per_page=100 -q ".[].name" | xargs -r -I{} gh api -X DELETE /repos/${{ github.repository }}/git/refs/tags/{}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
