name: Nuclear Clean

on:
  schedule:
    - cron: '0 16,4 * * *'
  workflow_dispatch:

jobs:
  obliterate:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      actions: write
      contents: write
      packages: write

    steps:
      - name: Setup GitHub CLI
        run: |
          sudo apt update
          sudo apt install -y gh
        if: ${{ !env.ACT }}  # Skip if running locally with ACT

      - name: Clean Workflow Runs
        run: |
          current_run=${{ github.run_id }}
          gh run list --limit 100 --json databaseId -q ".[] | select(.databaseId != $current_run) | .databaseId" |
            xargs -r gh run delete --yes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

      - name: Clean Action Caches
        run: gh cache delete --all --confirm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

      - name: Clean Releases
        run: |
          gh release list --limit 100 --json id -q ".[].id" |
            xargs -r gh release delete --yes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

      - name: Clean Tags
        run: |
          gh api repos/${{ github.repository }}/git/refs/tags --paginate -q '.[].ref' |
            sed 's/^refs\/tags\///' |
            xargs -r -I {} gh api -X DELETE repos/${{ github.repository }}/git/refs/tags/{}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
