name: Nuclear Clean

on:
  schedule:
    - cron: '0 16,4 * * *'
  workflow_dispatch:

jobs:
  clean:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      actions: write
      contents: write
    
    steps:
      - name: Setup Environment
        run: |
          sudo apt update
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          sudo apt install gh -y
          gh auth login --with-token <<< "$TOKEN"
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Secure Delete Workflow Runs
        run: |
          gh run list --json databaseId -q ".[].databaseId" | 
            grep -v $RUN_ID |
            xargs -I {} gh api \
              -H "Authorization: Bearer $TOKEN" \
              -H "Accept: application/vnd.github+json" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              --method DELETE \
              /repos/$REPO/actions/runs/{}
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUN_ID: ${{ github.run_id }}
          REPO: ${{ github.repository }}

      - name: Guaranteed Cache Purge
        run: |
          gh cache delete --all --confirm
        
      - name: Delete Releases
        run: |
          gh api -H "Authorization: Bearer $TOKEN" \
            -H "Accept: application/vnd.github+json" \
            /repos/$REPO/releases \
            --paginate -q '.[].id' | 
            xargs -I {} gh api -X DELETE /repos/$REPO/releases/{}
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
        
      - name: Delete Tags
        run: |
          gh api -H "Authorization: Bearer $TOKEN" \
            -H "Accept: application/vnd.github+json" \
            /repos/$REPO/git/refs/tags \
            --paginate -q '.[].ref' | 
            xargs -I {} gh api -X DELETE /repos/$REPO/git/refs/tags/{}
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
