name: Nuclear Clean

on:
  schedule:
    - cron: '0 16,4 * * *'
  workflow_dispatch:

jobs:
  obliterate:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    permissions:
      actions: write
      contents: write
      packages: write

    steps:
      - name: Nuclear Clean
        run: |
          gh run list -L 100 -q ".[] | select(.databaseId != ${{ github.run_id }}).databaseId" | xargs -r gh run delete -y 2>/dev/null || true
          gh cache delete -a -f 2>/dev/null || true
          gh release list -L 100 -q ".[].tagName" | xargs -r gh release delete -y --cleanup-tag 2>/dev/null || true
          gh api -H "Accept: application/vnd.github.v3+json" "/repos/${{ github.repository }}/tags?per_page=100" -q ".[].name" | xargs -r -I{} gh api -X DELETE "repos/${{ github.repository }}/git/refs/tags/{}" 2>/dev/null || true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
