name: Nuclear Clean

on:
  schedule:
    - cron: '0 16,4 * * *'  # 北京时间0:00和12:00
  workflow_dispatch:

jobs:
  obliterate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      actions: write
      contents: write
      packages: write

    steps:
      # 清理所有工作流运行记录
      - name: Clean Workflow Runs
        uses: kachick/delete-workflow-runs@v2
        with:
          skip_confirmation: true
          keep_min_runs: 1  # 保留当前运行
          ignore_active_runs: false
          token: ${{ secrets.GITHUB_TOKEN }}
      
      # 专门清理所有缓存（最核心的部分）
      - name: Purge All Caches
        uses: ethomson/clear-gha-caches@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          keep_min_caches: 0
          remove_older_than: 0
          force: true

      # 清理所有发布
      - name: Delete All Releases
        uses: YoavShapira/gh-actions-delete-releases@v1
        with:
          keep_min_releases: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      # 清理所有标签
      - name: Delete All Tags
        uses: YoavShapira/gh-actions-delete-tags@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          keep_min_tags: 0
